apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/nfd/subscription.yaml
  - infrastructure/servicemesh/subscription.yaml
  - infrastructure/serverless/subscription.yaml
  - rhoai-core/operator/subscription.yaml
  - rhoai-core/dsc/dsc.yaml
